<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LottieSharp" Version="2.4.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app.png" />
    <Resource Include="Assets\copy-bunny.json" />
    <Resource Include="Assets\cat-popping-box.gif" />
    <Resource Include="Assets\cat-popping-box.json" />
    <Resource Include="Assets\cat-layer-image_8.png" />
    <Resource Include="Assets\cat-layer-image_9.png" />
    <Resource Include="Assets\default-avatar.jpg" />
    <Resource Include="Assets\developer-cat.json" />
    <Resource Include="Assets\empty-box.json" />
    <Resource Include="Assets\empty-screen.json" />
    <Resource Include="Assets\empty-state.json" />
    <Resource Include="Assets\invalid-state.json" />
    <None Include="Assets\app-logo.svg" />
    <None Include="Assets\ai-generating-loading.json" />
    <None Include="Assets\loading-squares.json" />
  </ItemGroup>

</Project>
